### ISSUE TITLE
Issue 1 - Update

### ISSUE THREAD

**Issue by vincentsarago** [cogeotiff/rio-tiler-pds#1]
as of https://github.com/cogeotiff/rio-tiler-pds/commit/6c82b6e8d32e29e0346e36381cbcd8f6ca640ab7 the code is just a pure copy of rio-tiler code. 

I'd love to update each submodule to use ContextManager as `rio_tiler_io.COGReader` and `rio_tiler_io.STACReader`

# TO DO
- update code to use rio_tiler.io.cogeo.multi_* modules (replacement of rio_tiler.reader_multi) 
- decide and change the code architecture  https://github.com/cogeotiff/rio-tiler/issues/124#issuecomment-537968184

The idea behind moving all code here was to ease addition of new PDS (e.g next Landsat release from USGS, Sentinel2 COG....), I'm not sure what's the best way to do that.

**Comment by kylebarron** [comment]
The idea is that this package is basically a mapping from `scene_ids` -> `s3 path`, right? So it would make sense for a _single class_ per dataset, which can point to either AWS JP2 Sentinel 2, AWS COG Sentinel 2, or GCS Sentinel 2. 

Then e.g. on `sentinel2.tile`, it can have a `dataset` parameter that's either `s3_jp2`, `s3_cog`, or `gcs_jp2`.

**Comment by vincentsarago** [comment]
let's start a list of the dataset we know right now! 

Note: for some dataset it won't be possible to do `Id -> path` (e.g Landsat/Sentinel on GCS) but it's might still be interesting to handle it.

**Comment by vincentsarago** [comment]
FYI, I'm going to wait for https://github.com/cogeotiff/rio-tiler/pull/206 to get merged so we can use https://github.com/cogeotiff/rio-tiler/blob/MosaicReader/rio_tiler/io/base.py#L12 as base class for the new Readers 

```python
from rio_tiler.io.base import BaseReader

class L8_AWSPublicDataset_Reader(BaseReader):

    sceneid: str
    minzoom: int = 7
    maxzoom: int = 12

    # we can use __post_init__ to parse the sceneid and populate some metadata

    def __enter__(self):
        """Support using with Context Managers."""
        # get and parse MTL file
        # set self.bounds
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        """Support using with Context Managers."""
        if self.filepath:
            self.dataset.close()

    def metadata(self, ...)
    def info(self, ...)
    def stats(self, ...)
    def tile(self, ...)
    def part(self, ...)
    def preview(self, ...)
```
