### ISSUE TITLE
assets -> bands

### ISSUE THREAD

**Issue by vincentsarago** [cogeotiff/rio-tiler-pds#12]
for this new version I chose to use the word `assets` instead of `bands` to better align with STAC. This is in fact confusing and might also not help with migration. 

I propose (with @kylebarron) to move back to `bands`.

**Comment by kylebarron** [comment]
For more background:

> historically we’ve used asset in the Mosaic sense to refer to multiple “Items” in STAC terminology. E.g. `mosaic.assets_for_tile` gives a list of the identifiers included in the mosaic

> however STAC uses asset to mean “bands”. So now rio-tiler-pds uses asset to mean bands as well. E.g.

> so asset refers both to the url/sceneid _and_ the band
