### ISSUE TITLE
MODIS on AWS

### ISSUE THREAD

**Issue by Blockchainforcommons** [cogeotiff/rio-tiler-pds#18]
Hi, love your work. 

Is it possible to add MODIS? With it, we can build regression models to transpose Sen2 images for example NDVI. 

https://docs.opendata.aws/modis-pds/readme.html

**Comment by vincentsarago** [comment]
@Blockchainforcommons so this was done in #19. Thanks for pointing out the MODIS PDS. I also added the MODIS dataset managed by Astraea. 

Would be good if you could tests those before we cut a new release 

```bash
$  pip install git+https://github.com/cogeotiff/rio-tiler-pds.git
```

```python

from rio_tiler_pds.modis.aws import MODISPDSReader, MODISASTRAEAReader

with MODISPDSReader("{your modis scene}") as modis:
...
```
docs: https://cogeotiff.github.io/rio-tiler-pds/usage/#modis-aws
tests: https://github.com/cogeotiff/rio-tiler-pds/blob/master/tests/test_modis.py#L42
