### ISSUE TITLE
Argument to set threads for landsat tiler

### ISSUE THREAD

**Issue by kylebarron** [cogeotiff/rio-tiler-pds#4]
With the landsat tiler (and maybe others), it uses a `ThreadPoolExecutor` and you can't change the number of threads, it would be good to have that as an argument, similar to in `mosaic_reader`

https://github.com/cogeotiff/rio-tiler-pds/blob/9f96e9995ebf2d29ef4baad48c44b953d211a040/rio_tiler_pds/landsat8.py#L344

**Comment by vincentsarago** [comment]
FYI, all methods will forward the `threads` option to https://github.com/cogeotiff/rio-tiler/blob/master/rio_tiler/tasks.py#L50 

```python
with L8Reader("LC08_L1TP_016037_20170813_20170814_01_RT") as landsat: 
    print(landsat.stats(assets="BQA", threads=1))
```

**Comment by kylebarron** [comment]
So that means this is fixed then?

**Comment by vincentsarago** [comment]
Yes
